kind: pipeline
name: test1

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpine
    commands:
      - apk add git
      - git clone --depth=1 https://git.alpinelinux.org/aports/
      - cd aports/scripts
      - APORTS="" sh mkimage.sh