kind: pipeline

clone:
  disable: true

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    image: alpine
    commands:
      - apk add git
      - git clone --depth=1 https://git.alpinelinux.org/aports/
      - apk add abuild apk-tools alpine-conf busybox fakeroot mtools grub-efi
      - cd aports/scripts
      - sh mkimage.sh --profile minirootfs --repository http://dl-cdn.alpinelinux.org/alpine/edge/main/
  